# Generated by Django 5.2.3 on 2025-06-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='book',
            name='year',
        ),
        migrations.AddField(
            model_name='book',
            name='desc',
            field=models.CharField(default='desc', max_length=300),
        ),
        migrations.AddField(
            model_name='book',
            name='rate',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='book',
            name='views',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
