# Generated by Django 5.2.3 on 2025-06-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='added_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
