# Generated by Django 5.2.3 on 2025-06-19 13:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreApp', '0003_book_rate_book_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(validators=[django.core.validators.MinLengthValidator(2, 'category needs at least 2 characters')])),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=50, validators=[django.core.validators.MinLengthValidator(10, message='book title needs at least 10 characters')]),
        ),
        migrations.AddField(
            model_name='book',
            name='categories',
            field=models.ManyToManyField(related_name='books', to='bookstoreApp.category'),
        ),
    ]
