# Generated by Django 5.2.3 on 2025-06-19 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstoreApp', '0004_category_alter_book_title_book_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='ISBN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=13)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='isbn', to='bookstoreApp.book')),
            ],
        ),
    ]
